language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - 8
  - 10
  - 11
script:
  - 'npm run cover'
after_success:
  - 'npm run cover:up'
notifications:
  email: false
