language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - 4
  - 6
  - 7
before_script:
  - '(node -v | grep v6) && yarn add svelte fuse-box || exit 0'
script:
  - 'yarn cover'
after_success:
  - 'yarn cover:up'
notifications:
  email: false
