language: node_js
env:
  - CXX=g++-4.8
addons:
  apt:
    sources:
      - ubuntu-toolchain-r-test
    packages:
      - g++-4.8
node_js:
  - 8
  - 9
  - 10
before_script:
  - '(node -v | grep -e "v[681]") && npm install svelte sucrase fuse-box || echo SKIP'
script:
  - 'npm run cover'
after_success:
  - 'npm run cover:up'
notifications:
  email: false
